name: Build Docker Image

on:
  push:
    branches:
      - typescript
      - temp-*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runner with Docker installed
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 
      
      - name: Download client artifact from external repository
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build-react.yaml
          repo: WinterWolf98/json-viewer
          branch: catalyst
          name: react-build
          path: ./client

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f Dockerfile -t localhost/express-app:latest --platform linux/amd64 .
          docker save localhost/express-app:latest -o express-app.tar

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: express-app.tar

      - name: "Install ZCatalyst-CLI"
        run: |
          curl -fsS https://prasanna-10049-test-development.zohostratus.in/custom_runtime/cli/portable-cli.zip -o cli.zip
          unzip cli.zip -qq -d catalyst-cli

      - name: "Deploy to Catalyst"
        env:
          ZCATALYST_TOKEN: ${{ secrets.ZCATALYST_TOKEN }}
          ORG_ID: ${{ vars.ORG_ID }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
        run: |
          ./catalyst-cli/node_modules/.bin/catalyst -v
          ./catalyst-cli/node_modules/.bin/catalyst deploy appsail --source "docker://localhost/express-app:latest" --name "git-img" --token "${ZCATALYST_TOKEN}" --org 60035305391 --project 11533000000016001 --verbose

  deploy-tar:

    runs-on: ubuntu-latest  # GitHub Actions runner with Docker installed
    needs: build  # Ensure this job runs after the build job
    if: ${{ github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: .

      - name: List folder contents
        run: |
          ls -la

      - name: "Install ZCatalyst-CLI"
        run: |
          curl -fsS https://prasanna-10049-test-development.zohostratus.in/custom_runtime/cli/portable-cli.zip -o cli.zip
          unzip cli.zip -qq -d catalyst-cli

      - name: "Deploy to Catalyst"
        env:
          ZCATALYST_TOKEN: ${{ secrets.ZCATALYST_TOKEN }}
          ORG_ID: ${{ vars.ORG_ID }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
        run: |
          ./catalyst-cli/node_modules/.bin/catalyst -v
          ./catalyst-cli/node_modules/.bin/catalyst deploy appsail --source "docker-archive://./express-app.tar" --name "git-tar" --token "${ZCATALYST_TOKEN}" --org 60035305391 --project 11533000000016001 --verbose
